/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ansen_jnitest_JNITest */

#ifndef _Included_com_ansen_jnitest_JNITest
#define _Included_com_ansen_jnitest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ansen_jnitest_JNITest
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ansen_jnitest_JNITest_plus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
